### ISSUE TITLE
The difference between code and paper

### ISSUE THREAD

**Issue by unknowed-ER** [WHUIR/MGNM#2]
In model.py lines 262~273, it seem that you use dot product to measure the distance between items without considering user characteristics as stated in the paper.

```
        # whether apply user_emb
        if 1:
            adj = tf.nn.sigmoid(tf.reduce_sum(adj_l * adj_r, axis=-1))#tf.concat([adj_l, adj_r], axis=3)
            adj = adj * tf.expand_dims(self.mask, axis=1)
            adj = adj * tf.expand_dims(self.mask, axis=2)

        else:
	        adj_node = tf.multiply(adj_l, adj_r)
	        adj_user = tf.expand_dims(tf.expand_dims(self.user_eb, axis=1), axis=2)
	        adj = tf.nn.sigmoid(tf.reduce_sum(adj_node*adj_user, axis=-1))
	        adj = adj * tf.expand_dims(self.mask, axis=1)
	        adj = adj * tf.expand_dims(self.mask, axis=2)
```

In util_se.py lines 313~317,  it seems that the vectors in all_embeddings[1:] are all the representations after the first convolution, without iterative updating as in the paper.

```
    all_embeddings = [tf.slice(x, [0, se_num, 0], [batch_size, seq_len, embedding_dim])]
    for k in range(num_layer):
        embeddings = tf.matmul(A, x)
        embeddings = tf.nn.leaky_relu(tf.matmul(embeddings, all_weights['W_gc%d' % 0]) + all_weights['B_gc%d' % 0])
        all_embeddings.append(tf.slice(embeddings, [0, se_num, 0], [batch_size, seq_len, embedding_dim]))
```

Are the experimental results in your paper the results obtained using the current code training? 
I'm not sure if my understanding of the code is correct.
Looking forward to your reply.

**Comment by unknowed-ER** [comment]
It seems that you deleted the BiLSTM in CapsuleNetwork. 
How should I adjust the results in the paper?
I need more detailed guidance.

**Comment by lichenliang-whu** [comment]
The first place describes that there are two ways to build the graph, which is able to adjust. And the experiments are based on the paper.  The second difference is that I didn't modify it when I did the ablation experiment later. So It is a mistake. Thank you for your issue, I will correct it as soon as possible

**Comment by wy-0** [comment]
@unknowed-ER 
I think you have carefully studied the code of this paper. I want to ask you some questions about the operation. When I am running, I will report an error of 
"tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [256] vs. [252]
         [[{{node gradients/logistic_loss_3/mul_grad/BroadcastGradientArgs}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main()
  File "train.py", line 118, in main
    loss = model.train(sess, [user, tgt, hist, mask, label, LEARNING_RATE])
  File "/media/sdb2/AAAA_sdb2/zjp/MGNM/MGNM-main/code/model.py", line 79, in train
    loss, _ = sess.run([self.loss, self.optimizer], feed_dict=feed_dict)




tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [256] vs. [252]
         [[node gradients/logistic_loss_3/mul_grad/BroadcastGradientArgs (defined at /media/sdb2/AAAA_sdb2/zjp/MGNM/MGNM-main/code/model.py:60) ]]

Original stack trace for 'gradients/logistic_loss_3/mul_grad/BroadcastGradientArgs':
  File "train.py", line 144, in <module>
    main()
  File "train.py", line 99, in main
    model = modelTy(item_count, user_count, DIMENSION, BATCH_SIZE, SEQ_LEN, NEG_NUM, HIDDEN_SIZE, NUM_PREFERENCE, NUM_LAYER, SE_NUM)
  File "/media/sdb2/AAAA_sdb2/zjp/MGNM/MGNM-main/code/model.py", line 299, in __init__
    self.build_multi_ce_loss(self.item_eb, user_eb_list)
  File "/media/sdb2/AAAA_sdb2/zjp/MGNM/MGNM-main/code/model.py", line 60, in build_multi_ce_loss
    self.optimizer = tf.train.AdamOptimizer(learning_rate=self.lr).minimize(self.loss)

". 
How to solve this problem?
thank you

**Comment by unknowed-ER** [comment]
@wy-0 
Sorry, I shouldn't be able to give you any useful suggestions.  I have not encountered this problem and I am not familiar with the tf framework.

**Comment by wy-0** [comment]
@unknowed-ER 
Ok, I got it. Thank you for your reply.

**Comment by wy-0** [comment]
@unknowed-ER 
Have you run through this code? If it is convenient, can you send me the source code and environment configuration you ran through? Thank you very much!

**Comment by unknowed-ER** [comment]
@wy-0 
I didn't change the source code the authers proposed, and the environment is following.  
```
Package              Version
-------------------- ---------
absl-py              1.2.0
astor                0.8.1
cachetools           5.2.0
certifi              2022.6.15
charset-normalizer   2.1.0
click                8.1.3
elastic-transport    8.1.2
elasticsearch        8.3.3
funcsigs             1.0.2
gast                 0.5.3
google-pasta         0.2.0
grpcio               1.48.0
h5py                 3.7.0
idna                 3.3
importlib-metadata   4.12.0
joblib               1.1.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
Markdown             3.4.1
MarkupSafe           2.1.1
nltk                 3.7
numpy                1.16.6
nvidia-ml-py         11.495.46
nvitop               0.7.2
packaging            21.3
pandas               1.1.5
pathlib              1.0.1
pip                  22.1.2
protobuf             3.20.1
psutil               5.9.1
pyparsing            3.0.9
python-dateutil      2.8.2
pytz                 2022.2
PyYAML               6.0
regex                2022.7.25
requests             2.28.1
scikit-learn         1.0.2
scipy                1.7.3
sentencepiece        0.1.97
setuptools           61.2.0
six                  1.16.0
sklearn              0.0
tensorboard          1.14.0
tensorboardX         2.5.1
tensorflow           1.14.0
tensorflow-estimator 1.14.0
tensorflow-gpu       1.14.0
termcolor            1.1.0
texar                0.2.4
threadpoolctl        3.1.0
tqdm                 4.64.0
typing_extensions    4.3.0
urllib3              1.26.11
Werkzeug             2.2.1
wheel                0.37.1
wrapt                1.14.1
zipp                 3.8.1
```
I have also implemented MGNM under pytorch, you can run it in the following path: ReChorus\src\models\sequential\
You can get all the code of ReChorus from here. https://github.com/THUwangcy/ReChorus
Although I try my best to implement it, I do not guarantee the accuracy of the implementation code.

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

from models.BaseModel import SequentialModel


class MGNM(SequentialModel):
    extra_log_args = ['emb_size', 'interest_num']

    @staticmethod
    def parse_model_args(parser):
        parser.add_argument('--emb_size', type=int, default=64, help='Size of embedding vectors.')
        parser.add_argument('--interest_num', type=int, default=4, help='Number of hidden intent.')
        parser.add_argument('--num_layer', type=int, default=4, help='Number of hidden intent.')
        parser.add_argument('--hard_readout', type=bool, default=False, help='Number of hidden intent.')
        parser.add_argument('--relu_layer', type=bool, default=False, help='Number of hidden intent.')
        return SequentialModel.parse_model_args(parser)

    def __init__(self, args, corpus):
        self.emb_size = args.emb_size
        super().__init__(args, corpus)
        self.interest_num = args.interest_num
        self.max_his = args.history_max
        self.num_layer = args.num_layer
        self.hard_readout = args.hard_readout
        self.relu_layer = args.relu_layer
        self.len_range = torch.from_numpy(np.arange(self.max_his)).to(self.device)

        self.gcn_linear = nn.Linear(self.emb_size, self.emb_size)

        self.capsule_network = BiLSTMCapsuleNetwork(self.emb_size, self.history_max, bilinear_type=2,
                                          interest_num=self.interest_num,
                                          routing_times=3,
                                          hard_readout=self.hard_readout,
                                          relu_layer=self.relu_layer,
                                          device = self.device)

    def _define_params(self):
        self.item_eb = nn.Embedding(self.item_num, self.emb_size)
        self.user_eb = nn.Embedding(self.user_num, self.emb_size)


    def forward(self, feed_dict):
        self.check_list = []
        i_ids = feed_dict['item_id']  # [batch_size, -1]
        history = feed_dict['history_items']  # [batch_size, history_max]
        lengths = feed_dict['lengths']  # [batch_size]
        batch_size, seq_len = history.shape

        # 因为capsule_network是固定大小的，所以要固定batch
        if seq_len < self.max_his:
            history = torch.cat((history, torch.zeros((batch_size, self.history_max - seq_len), dtype=torch.int64, device=self.device)), dim=-1)
        batch_size, seq_len = history.shape

        valid_his = history.gt(0)
        item_his_eb = self.item_eb(history)
        item_his_eb[~valid_his] = 0
        adj_l = item_his_eb.unsqueeze(2).expand(-1, -1, seq_len, -1)
        adj_r = item_his_eb.unsqueeze(1).expand(-1, seq_len, -1, -1)

        adj = torch.sigmoid((adj_l * adj_r).sum(dim=-1))
        adj = adj * valid_his.unsqueeze(1)
        adj = adj * valid_his.unsqueeze(2)

        adj_l1 = torch.norm(adj, p=1)

        all_embedding = self._create_gcn_emb(adj, item_his_eb, self.num_layer - 1, self.emb_size, 0, batch_size, seq_len, layer_size=[self.emb_size, self.emb_size, self.emb_size])
        user_eb_list = []
        mask_new = valid_his
        i_vectors = self.item_eb(i_ids)
        for l in range(self.num_layer):
            user_eb, readout = self.capsule_network(all_embedding[l], i_vectors, mask_new)
            user_eb_list.append(readout)

        interest_vectors = torch.stack(user_eb_list, dim=1)

        prediction = (interest_vectors * i_vectors.unsqueeze(1)).sum(-1).max(1)[0]

        return {'prediction': prediction.view(batch_size, -1), 'adj_l1': adj_l1}

    def loss(self, out_dict: dict):
        loss = super(MGNM, self).loss(out_dict)
        loss += out_dict['adj_l1'] * 1e-6
        return loss

    def _create_gcn_emb(self, A, x, num_layer, embedding_dim, se_num, batch_size, seq_len, layer_size=[64, 64, 64]):
        # initializer = nn.init.normal_
        # weights_size_list = [embedding_dim] + layer_size
        # all_weights = {}
        # for lay in range(1):
        #     all_weights['W_gc%d' % lay] = nn.Parameter(initializer(torch.empty(weights_size_list[lay], weights_size_list[lay + 1]), std=0.01))
        #     all_weights['B_gc%d' % lay] = nn.Parameter(initializer(torch.empty(1, weights_size_list[lay + 1]), std=0.01))

        # gcn has three layers
        all_embeddings = [x]
        for k in range(num_layer):
            embeddings = A.matmul(all_embeddings[k])
            embeddings = torch.nn.LeakyReLU()(self.gcn_linear(embeddings))
            all_embeddings.append(embeddings)

        return all_embeddings


class BiLSTMCapsuleNetwork(nn.Module):
        def __init__(self, hidden_size, seq_len, bilinear_type=2, interest_num=4, routing_times=3, hard_readout=True, relu_layer=False,
                     device='cpu'):
            super(BiLSTMCapsuleNetwork, self).__init__()
            self.hidden_size = hidden_size  # h
            self.seq_len = seq_len  # s
            self.bilinear_type = bilinear_type
            self.interest_num = interest_num
            self.routing_times = routing_times
            self.hard_readout = hard_readout
            self.relu_layer = relu_layer
            self.stop_grad = True
            self.device = device
            self.relu = nn.Sequential(
                nn.Linear(self.hidden_size, self.hidden_size, bias=False),
                nn.ReLU()
            )
            if self.bilinear_type == 0:  # MIND
                self.linear = nn.Linear(self.hidden_size, self.hidden_size, bias=False)
            elif self.bilinear_type == 1:
                self.linear = nn.Linear(self.hidden_size, self.hidden_size * self.interest_num, bias=False)
            else:  # ComiRec_DR
                self.w = nn.Parameter(nn.init.normal_(torch.empty(1, self.seq_len, self.interest_num * self.hidden_size, self.hidden_size)))

            self.biLSTM = nn.LSTM(input_size=self.hidden_size * self.interest_num, hidden_size=self.hidden_size, bidirectional=True, batch_first=True)
            self.biLSTM_linear = nn.Linear(self.hidden_size * 2, self.hidden_size * self.interest_num)

        def forward(self, item_eb, i_vectors, mask):
            if self.bilinear_type == 0:  # MIND
                item_eb_hat = self.linear(item_eb)  # [b, s, h]
                item_eb_hat = item_eb_hat.repeat(1, 1, self.interest_num)  # [b, s, h*in]
            elif self.bilinear_type == 1:
                item_eb_hat = self.linear(item_eb)
            else:  # ComiRec_DR
                u = torch.unsqueeze(item_eb, dim=2)  # shape=(batch_size, maxlen, 1, embedding_dim)
                item_eb_hat = torch.sum(self.w[:, :self.seq_len, :, :] * u, dim=3)  # shape=(batch_size, maxlen, hidden_size*interest_num)

            item_eb_hat = torch.reshape(item_eb_hat, (-1, self.seq_len, self.interest_num, self.hidden_size))
            item_eb_hat = torch.transpose(item_eb_hat, 1, 2).contiguous()
            # item_eb_hat = torch.reshape(item_eb_hat, (-1, self.interest_num, self.seq_len, self.hidden_size))

            # [b, in, s, h]
            if self.stop_grad:  # 截断反向传播，item_emb_hat不计入梯度计算中
                item_eb_hat_iter = item_eb_hat.detach()
            else:
                item_eb_hat_iter = item_eb_hat

            # b的shape=(b, in, s)
            if self.bilinear_type > 0:  # b初始化为0（一般的胶囊网络算法）
                capsule_weight = torch.zeros(item_eb_hat.shape[0], self.interest_num, self.seq_len, device=self.device, requires_grad=False)
            else:  # MIND使用高斯分布随机初始化b
                capsule_weight = torch.randn(item_eb_hat.shape[0], self.interest_num, self.seq_len, device=self.device, requires_grad=False)

            for i in range(self.routing_times):  # 动态路由传播3次
                atten_mask = mask.unsqueeze(1).repeat(1, self.interest_num, 1)  # [b, in, s]
                paddings = torch.zeros_like(atten_mask, dtype=torch.float)

                # 计算c，进行mask，最后shape=[b, in, 1, s]
                capsule_softmax_weight = F.softmax(capsule_weight, dim=-1)
                capsule_softmax_weight = torch.where(torch.eq(atten_mask, 0), paddings, capsule_softmax_weight)  # mask
                capsule_softmax_weight = torch.unsqueeze(capsule_softmax_weight, 2)

                if i < 2:
                    # s=c*u_hat , (batch_size, interest_num, 1, seq_len) * (batch_size, interest_num, seq_len, hidden_size)
                    interest_capsule = torch.matmul(capsule_softmax_weight, item_eb_hat_iter)  # shape=(batch_size, interest_num, 1, hidden_size)
                    cap_norm = torch.sum(torch.square(interest_capsule), dim=-1, keepdim=True)  # shape=(batch_size, interest_num, 1, 1)
                    scalar_factor = cap_norm / (1 + cap_norm) / torch.sqrt(cap_norm + 1e-9)  # shape同上
                    interest_capsule = scalar_factor * interest_capsule  # squash(s)->v,shape=(batch_size, interest_num, 1, hidden_size)

                    # 更新b， 就是论文里的g
                    delta_weight = torch.matmul(item_eb_hat_iter,
                                                # shape=(batch_size, interest_num, seq_len, hidden_size)
                                                torch.transpose(interest_capsule, 2, 3)
                                                # shape=(batch_size, interest_num, hidden_size, 1)
                                                )  # u_hat*v, shape=(batch_size, interest_num, seq_len, 1)
                    delta_weight = torch.reshape(delta_weight, (-1, self.interest_num, self.seq_len))  # shape=(batch_size, interest_num, seq_len)
                    capsule_weight = capsule_weight + delta_weight  # 更新b
                    # 加入BiLSTM
                    if i == 0:
                        item_emb_lstm_input = item_eb_hat.detach().reshape(-1, self.seq_len, self.interest_num*self.hidden_size)
                        item_emb_lstm_output = self.biLSTM(item_emb_lstm_input)[0]
                        item_eb_hat_iter = self.biLSTM_linear(item_emb_lstm_output).reshape([-1, self.interest_num, self.seq_len, self.hidden_size])
                        item_eb_hat_iter = item_eb_hat_iter + item_eb_hat.detach()
                    else:
                        item_eb_hat_iter = item_eb_hat.detach()

                else:
                    interest_capsule = torch.matmul(capsule_softmax_weight, item_eb_hat)
                    cap_norm = torch.sum(torch.square(interest_capsule), -1, True)
                    scalar_factor = cap_norm / (1 + cap_norm) / torch.sqrt(cap_norm + 1e-9)
                    interest_capsule = scalar_factor * interest_capsule

            interest_capsule = torch.reshape(interest_capsule, (-1, self.interest_num, self.hidden_size))

            if self.relu_layer:  # MIND模型使用book数据库时，使用relu_layer
                interest_capsule = self.relu(interest_capsule)

            atten = interest_capsule.matmul(i_vectors.transpose(-2, -1))
            atten = F.softmax(atten, dim=1)

            if self.hard_readout:
                readout = interest_capsule.reshape(-1, self.hidden_size).gather(index=atten.argmax(dim=1).long()+torch.arange(item_eb.shape[0]) * self.interest_num)
            else:
                readout = atten.transpose(-1, -2).matmul(interest_capsule)

            return interest_capsule, readout
```

**Comment by wy-0** [comment]
@unknowed-ER 
Wonderful !  Thank you very much !
